config/routes.rb
Rails.application.routes.draw do

  # display all:
  get 'tasks', to: "tasks#index", as: :tasks

  #create a new task (first get data, then send it)
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  # show one item:
  get 'tasks/:id', to: "tasks#show", as: :task

  # update one item:
  get    "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch  "tasks/:id", to: "tasks#update"

  #delete one item:
  delete "tasks/:id", to: "tasks#destroy", as: :delete_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
     @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title%>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details%>
  </div>

   <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed %>

  </div>

  <%= f.submit value: "Edit Task"%>

<% end %>

app/views/tasks/index.html.erb
<h2>List of tasks</h2>

<ul style="list-style-type: none">
  <% @tasks.each do |task| %>
    <li>
        <% if task.completed %>
          <input type = "checkbox" disabled checked>
        <% else %>
          <input type = "checkbox" disabled>
        <% end %>
       <%= link_to task.title, task_path(task) %>
       <%= link_to(delete_task_path(task), method: :delete, data: { confirm: "Are you sure?" } ) do %>
         <i class= "far fa-trash-alt"> </i>
       <% end %>
     </li>
  <% end %>
</ul>

<p><%= link_to "Add a new task", new_task_path %> </p>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title%>
  </div>
  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details%>
  </div>
   <%= f.submit value: "Create Task"%>
<% end %>

app/views/tasks/show.html.erb
<h2>  <%= @task[:title]  %></h2>

<p><%= @task[:details]  %> </p>

<p>
  <% if @task[:completed] %>
    <input type = "checkbox" disabled checked>
  <% else %>
    <input type = "checkbox" disabled>
  <% end %>
</p>


<p><%= link_to "Edit this task", edit_task_path %></p>
<p><%= link_to "Back to list", tasks_path %> </p>